
const HANDLESUBMIT = 'handlesubmit';
const LOGGED_IN = 'LOGGED_IN';
const LOGGED_OUT = 'LOGGED_OUT';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export {
  HANDLESUBMIT, LOGGED_IN, LOGGED_OUT, LOGIN_SUCCESS,
};
